language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - curl -sL -o ./kelda https://github.com/kelda/kelda/releases/download/dev/kelda_linux
        && chmod +x ./kelda

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint
    - ./kelda inspect ./kibanaExample.js graphviz

notifications:
    slack:
        secure: FAIMR3gajLiMk0A2+Vpd+c8Apb4d7YPra/lUCmYrbsGtYwYuecvzzrUk8LUkrIJPZUZ92p4eO/5dW4vApbfACvNrbCTgop3jlsxcvzgDUfEAsfRtJVq2TEX/32qxXEtD6QgsJCWm/LjWH3rd9pN6YvBDlWXg4pBPIQDD8c3x3jbi9htCJI3OSdg5yK5IL/GMCLI0XGwh3QeJ6vRUCgzdAoCCTZ/GPl2n6patWuJnGq42qsQXFKnS9tFMAxMC70f8bLdEeiGCcx9OXYnaJGq4Xd3xFdDdbZJYtXcZ71tMhCMVpKRuGdRJAIbzG4DQ2fTF7UBrOnNpntjnsVSw0OFEzr8A1YJPAFL1swZsWgP3PIUzhXQa0g6eDQXHSc2GFkoJSp6m2gQZqoAEDiMsTARBHq49jNiA0bsRhIeYyfuvkMYwPVlkaNvocsivZWTBYqgRYIOynPQWA/GKJCDeYI9LZKBV9jYeoHkL5RVAD1ZDRQBQpzAe1vDOAGcu0zQQSyTkK6hxg92aYKfb/IMVUetOZR155EnifBlDi5flN5dDGaYaBDC+iYZ1OpFACtJzTE0/rz6cLTk4UuQBkWawlfPuUYFEuOaoFXaxYFzIFBPGBVPhNv3sRnhU5K/cQugKpwaFNmbQirmFKHM0FB9PTgKMp96T5ucFUojkF+c0z7P9AfI=
